apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: apm-server
  namespace: observability
spec:
  version: 8.7.1
  count: 1
  elasticsearchRef:
    name: elasticsearch
  kibanaRef:
    name: kibana