apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata:
  name: elastic-agent
  namespace: observability
spec:
  version: 8.7.0
  kibanaRef:
    name: kibana
  mode: fleet
  fleetServerEnabled: false
  fleetServerRef:
    name: fleet-server
  daemonSet:
    podTemplate:
      spec:
        serviceAccountName: elastic-agent
        automountServiceAccountToken: true
        securityContext:
          runAsUser: 0
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: elastic-agent
rules:
- apiGroups: [""] 
  resources:
  - pods
  - nodes
  - nodes/metrics
  - nodes/proxy
  - nodes/stats
  - nodes/log
  - events
  - namespaces
  - secrets
  - persistentvolumeclaims
  - persistentvolumes
  verbs:
  - get
  - list
  - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: elastic-agent
  namespace: observability
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: elastic-agent
subjects:
- kind: ServiceAccount
  name: elastic-agent
  namespace: observability
roleRef:
  kind: ClusterRole
  name: elastic-agent
  apiGroup: rbac.authorization.k8s.io